### ISSUE TITLE
Errors of installing rlpy through Pypi

### ISSUE THREAD

**Issue by originholic** [rlpy/rlpy#15]
Hello,
I tried to install the RLPy for the first time using command:
```
pip install -U rlpy
```
But I got following errors:
```
Error compiling Cython file:
------------------------------------------------------------
...
from libcpp cimport bool
cimport numpy as np
import numpy as np
cimport cython
ctypedef unsigned int uint
cimport c_kernels
       ^
------------------------------------------------------------

rlpy\Representations\kernels.pyx:15:8: 'c_kernels.pxd' not found

Error compiling Cython file:
------------------------------------------------------------
...
    cdef np.ndarray[double, ndim=2, mode="c"] s1 = widths
    x1 = np.ascontiguousarray(x, dtype=np.float64)
    cdef int i

    for i in xrange(len(centers)):
        res[i] = c_kernels.gaussian_kernel(&x1[0], &y1[i,0], dimv, &s1[i, 0])
                                          ^
------------------------------------------------------------

rlpy\Representations\kernels.pyx:59:43: Cannot convert 'double *' to Python object
```
I also tried to install it using setup.py file without any success due to:

```
rlpy/Representations/c_kernels.cc(37) : error C3861: 'fmin': identifier not found
```

I had my python environment installed with:
64-bit windows 7 Professional
Anaconda with conda version 3.18.6
Microsoft Visual C++ Compiler for Python 2.7

I tried to find the errors on google, the error C3861 'fmin' seems caused by the lake of C99 feature of visual studio, does this mean I need to install studio as well? or have I missed any dependencies?

**Comment by chrodan** [comment]
Do you still have the same issue when installing the current master? Commit fa27e7f1fe113 should have solved the fmin issue on VC++.

**Comment by originholic** [comment]
Hello,
Thanks a lot, although I haven't tried the most current master yet, but the previously downloaded rlpy installed smoothly now after changing the fmin to std::min.
